@baseUrl = http://localhost:3001/mcp/v1
// IMPORTANT: Replace the placeholder below with the actual value of
// "ExpectedToken" from your appsettings.json file.
@token = YOUR_SUPER_SECRET_AND_UNIQUE_TOKEN_REPLACE_ME
@mcpSessionId = K2PEu780HS1E1nDbfuNHNQ
## 2025-03-26
@mcpProtocolVersion = 2025-06-18

### "Discover" Request
# 2. (TOOLS/LIST) - Run this request SECOND
# (see mcp-listen.http)
# The response will appear in the *first* request's window.
POST {{baseUrl}}/claims/message?sessionId={{mcpSessionId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "jsonrpc": "2.0",
  "method": "tools/list",
  "params": {},
  "id": "msg-1"
}

###
# 3. (TOOLS/CALL) - Run this request SECOND
# (see mcp-listen.http)
# The response will appear in the *first* request's window.
POST {{baseUrl}}/claims/message?sessionId={{mcpSessionId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "jsonrpc": "2.0",
  "method": "tools/call",
  "params": {
    "name": "general-get_app_version",
    "arguments": { }
  },
  "id": "msg-2"
}

###
# 4. (TOOLS/CALL) - Run this request SECOND
# (see mcp-listen.http)
# The response will appear in the *first* request's window.
POST {{baseUrl}}/claims/message?sessionId={{mcpSessionId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "jsonrpc": "2.0",
  "method": "tools/call",
  "params": {
    "name": "identity-get_claims",
    "arguments": {
        "queryIncomingDto":{
          "Skipped": 0,
          "NumberOf": 70
        }
    }
    
  },
  "id": "msg-3"
}

